services:
  douglas:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - type: bind
        source: ../../../AUV-2024
        target: /AUV-2024
    image: "mcgillrobotics/auv_2024:jetson"
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - UDEV=on

    runtime: nvidia
    command: bash -c "ln -s /zed /AUV-2024/catkin_ws/src/zed && rm /zed/zed | exit 0 && tail -f /dev/null"
    network_mode: host
    restart: always
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # zed:
  #   volumes:
  #     - /dev:/dev
  #   image: "stereolabs/zed:4.1-py-runtime-jetson-jp6.0.0"
  #   privileged: true
  #   environment:
  #     - DISPLAY
  #     - QT_X11_NO_MITSHM=1
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - UDEV=on
  #   volumes:
  #     - /dev:/dev
  #   image: "stereolabs/zed:4.1-py-runtime-jetson-jp6.0.0"
  #   privileged: true
  #   environment:
  #     - DISPLAY
  #     - QT_X11_NO_MITSHM=1
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - UDEV=on
  #   runtime: nvidia
  #   command: bash -c "ln -s /zed /AUV-2024/catkin_ws/src/zed && rm /zed/zed | exit 0 && tail -f /dev/null"
  #   network_mode: host
  #   restart: always
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]