services:
  douglas:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - type: bind
        source: ../../../AUV-2024
        target: /AUV-2024
    image: "mcgillrobotics/auv_2024:jetson"
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - UDEV=on

    runtime: nvidia
    command: bash -c "echo 'source /root/AUV-2024/scripts/set_env.bash' >> ~/.bashrc && tail -f /dev/null"
    network_mode: host
    restart: always
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
