version: '3.8'
services:
  # Image Configurations for ROS 1 (Pulled from AUV-2024 Docker Hub)
  douglas:
    build: 
      context: ../../.
      dockerfile: Docker/bridge/Dockerfile
    volumes:
      - douglas:/var/lib/ros1/data
    networks:
      - ros-network
    environment:
      - ROS_MASTER_URI=http://localhost:11311/
        # For reference, check domain ID documentation for ROS 2 Humble
        # Default value: 0
      - ROS_DOMAIN_ID=0 
      # Configure ROS Install Paths for ROS 1 Bridge
      - ROS1_INSTALL_PATH=/opt/ros/noetic
      - ROS2_INSTALL_PATH=/opt/ros/humble
      
    stdin_open: true
    tty: true
  
volumes:
  douglas:

networks:
  ros-network:
    driver: bridge