services:
  clarke:
    environment:
      - DISPLAY=novnc:0.0
    volumes:
      - ../../AUV-2024:/root/AUV-2024
    image: "mcgillrobotics/auv_2024:unity"
    command: bash -c "tail -f /dev/null"
    ports:
      - "10000:10000"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]


  novnc:
    image: theasp/novnc:latest
    ports:
      - "8080:8080"
    environment:
      - RUN_XTERM=no
    