services:
  clarke:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../AUV-2024:/AUV-2024
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
    image: "mcgillroboticsteam/auv_2024:main"
    command: bash -c "tail -f /dev/null"
    runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]