services:
  clarke:
    volumes:
      - type: bind
        source: ../../../AUV-2024
        target: /root/AUV-2024
    image: "mcgillrobotics/auv_2024:main"
    command: bash -c "tail -f /dev/null"
    ports:
      - "10000:10000"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
