services:
  clarke:
    volumes:
      - ../../AUV-2024:/root/AUV-2024
    image: "mcgillroboticsteam/auv_2024:main"
    command: bash -c "tail -f /dev/null"
    network_mode: host
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]