#! ~/.tmuxinator/AUV-2020.yml

name: MAIN
root: /home/osboxes/Robotics/AUV-2020

pre: export SHELL=/bin/zsh && export PATH=/usr/local/sbin/:/usr/local/bin/:/usr/sbin:${PATH}:/sbin:/usr/games:/usr/local/games

windows:
  - core:
      panes:
        - roscore
  - state estimation:
      layout: tiled
      panes:
        - roslaunch state_estimation state_estimation.launch
        - roslaunch arduino arduino.launch
  - controls:
      panes:
        - roslaunch controls controls.launch
  - cameras:
      panes:
        - roslaunch cv camera_all.launch
  - hydrophones & nucleo:
      layout: tiled
      panes:
        - roslaunch hydrophones hydrophones.launch
        - roslaunch nucleo nucleo.launch
  - mission planner:
      panes:
        - roslaunch planner planner.launch