services:
  clarke:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../AUV-2024:/root/AUV-2024
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    build: .
    image: "docker.io/mcgillroboticsteam/auv_2024:trottier"
    networks:
      - podman
    ports:
      - 354:22
    command: ["/usr/sbin/sshd","-D"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
networks:
  podman:
    name: podman
    external: true