name: Catkin Build

on:
  pull_request:
    branches: [noetic]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: tonybob/auv_2024:main
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: |
            scripts/install_for_actions.sh
            source /opt/ros/noetic/setup.bash
            cd catkin_ws
            catkin build
