name: Catkin Build

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: osrf/ros:noetic-desktop-full
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: scripts/install_for_actions.sh
      - name: Build
        working-directory: catkin_ws
        run: catkin build
