name: Catkin Build

on:
  pull_request:
    branches: [noetic]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: tonybob/auv_2024:main
    steps:
      - uses: actions/checkout@v3
      - name: catkin build
        shell: bash
        run: |
            source /opt/ros/noetic/setup.bash
            cd catkin_ws
            catkin build
