name: Close issue

on:
    issues:
        types: [closed]

env:
    DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v3
        - run: |
            pip install -U discord.py
            python .github/discord_bot.py ${{ github.event.issue.assignees }}"
      