name: Close issue

on:
    issues:
        types: [closed]
env:
    SUPER_SECRET: ${{ secrets.DISCORD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - shell: bash
        - uses: actions/checkout@v3
        - run: |
            pip install -U discord.py
            python .github/discord_bot.py "$SUPER_SECRET"
            
