name: Catkin Build

on:
  pull_request:
    branches: [noetic]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: mcgillroboticsteam/auv_2024:main
    steps:
      - uses: actions/checkout@v3
      - name: catkin build
        shell: bash
        run: |
            git submodule update --init --recursive
            source /opt/ros/noetic/setup.bash
            cd catkin_ws
            catkin build
      - name: simple test
        shell: bash
        run: |
            cd catkin_ws
            source devel/setup.bash
            rostest planner testMission.launch
