name: Integration Test

on:
  pull_request:
    branches: [noetic]

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test certificate verification
        shell: bash
        run: |
          chmod +x .github/scripts/check_test_cert 
          ./.github/scripts/check_test_cert